# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b62b06ab0dda4b4bf273ea5f7fa48940ccfcc9ee07dde314b337247aa2c2592cbf3c3666011264d5d213c0386586592ad159e4439c87a362952f662c89e07dd

test:
  secret_key_base: 9060378fd04b1c87ef20104937496fe9cf3e52f8a70c7e6436d65796bcfe2878bc997f052ff44199c7b4c6a17e128e6bc28ff8dfc71dafbe64f44ea73816d673

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
